// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ZCL.Models;

#nullable disable

namespace ZCM_Console.Migrations
{
    [DbContext(typeof(ServiceDBContext))]
    partial class ServiceDBContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.2");

            modelBuilder.Entity("ZCL.Models.Service", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("address")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("peerGuid")
                        .HasColumnType("TEXT");

                    b.Property<ushort>("port")
                        .HasColumnType("INTEGER");

                    b.HasKey("id");

                    b.HasIndex("name", "address", "port", "peerGuid")
                        .IsUnique();

                    b.ToTable("Services");
                });
#pragma warning restore 612, 618
        }
    }
}
